# Site settings
author: Harley
title: Learning curve
header-img: img/home-bg.png
email: hmcdowell95@gmail.com
copyright_name: Harley
description: > # this means to ignore newlines until "baseurl:"
  My path to learn code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  hmcdowell95

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
